
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


# init - backend
- task: TerraformTaskV4@4
  displayName: Terraform Init
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'aws-rust-terraform-lession-1'
    backendAWSBucketName: 'rust-terraform-lession-1'
    backendAWSKey: 'kubernetes-dev.tfstate'

# validate
- task: TerraformTaskV4@4
  displayName: Terraform validate
  inputs:
    provider: 'aws'
    command: 'validate'

# plan
- task: TerraformTaskV4@4
  displayName: Terraform plan
  inputs:
    provider: 'aws'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-rust-terraform-lession-1'

# apply
- task: TerraformTaskV4@4
  displayName: Terraform apply
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-rust-terraform-lession-1'